# Load Boston data set
library(MASS)
mount(Boston)

par(mfrow=c(2,7))
plot(crim,  crim); abline(lm(crim~crim)) 
plot(zn,    crim); abline(lm(crim~zn)) 
plot(indus, crim); abline(lm(crim~indus)) 
plot(chas,  crim); abline(lm(crim~chas))
plot(nox,   crim); abline(lm(crim~nox)) 
plot(rm,    crim); abline(lm(crim~rm))  
plot(age,   crim); abline(lm(crim~age))  
plot(dis,   crim); abline(lm(crim~dis))  
plot(rad,   crim); abline(lm(crim~rad))  
plot(tax,   crim); abline(lm(crim~tax))    
plot(ptratio, crim); abline(lm(crim~ptratio))
plot(black, crim); abline(lm(crim~black))
plot(lstat, crim); abline(lm(crim~lstat))
plot(medv,  crim); abline(lm(crim~medv))

summary(lm(crim~., data=Boston))

predictors <- names(Boston)
y <- coefficients(lm(crim~., data=Boston))
x <- vector(mode="numeric", length=1)
x <- append(x,coefficients(lm(crim~zn))[[2]])
x <- append(x,coefficients(lm(crim~indus))[[2]])
x <- append(x,coefficients(lm(crim~chas))[[2]])
x <- append(x,coefficients(lm(crim~nox))[[2]])
x <- append(x,coefficients(lm(crim~rm))[[2]])
x <- append(x,coefficients(lm(crim~age))[[2]])
x <- append(x,coefficients(lm(crim~dis))[[2]])
x <- append(x,coefficients(lm(crim~rad))[[2]])
x <- append(x,coefficients(lm(crim~tax))[[2]])
x <- append(x,coefficients(lm(crim~ptratio))[[2]])
x <- append(x,coefficients(lm(crim~black))[[2]])
x <- append(x,coefficients(lm(crim~lstat))[[2]])
x <- append(x,coefficients(lm(crim~medv))[[2]])

df <- data.frame(predictors,x,y)

library(ggplot2)
library(ggrepel)
ggplot(df, aes(x,y)) + geom_point() + geom_text_repel(aes(x,y,label=predictors)) + coord_cartesian(xlim=c(-5,5),ylim=c(-5,5))