version: "3.7"
services:
  postgres:
    container_name: postgres_bhosl2
    image: postgres:12.1
    restart: always
    environment:
      POSTGRES_DB: myDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ######
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pgnet

  pgadmin:
    container_name: pgAdmin_bhosl2
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: bhosl2@uis.edu
      PGADMIN_DEFAULT_PASSWORD: ######
      PGADMIN_LISTEN_ADDRESS: 0.0.0.0
      PGADMIN_LISTEN_PORT: 5050
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:5050"
    networks:
      - pgnet
    links:
      - "postgres:pgsql-server"

  portainer:
    container_name: portainer_bhosl2
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer-data:/var/lib/data
    ports:
      - "9000:9000"
      - "8000:8000"
    networks:
      - pgnet

networks:
  pgnet:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:
